"""empty message

Revision ID: 697a96937d1b
Revises: dbba255ad984
Create Date: 2024-09-07 23:43:11.732005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697a96937d1b'
down_revision = 'dbba255ad984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###
